platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
- name: spring-concourse-demo

outputs:
- name: build-output

run:
  path: "demo/concourse/tasks/build.sh"
    